import Header from "@/components/default-layout/header/Header";
import ClientRootLayout from "@/components/shared/ClientRootLayout";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import "../../style.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <Header />
        <ClientRootLayout session={session}>{children}</ClientRootLayout>
      </body>
    </html>
  );
}
